#include <iostream>
#include "vectorSum.h"//header of the cuda object
#include "CudaHandler.h"

//method who implement the call to cuda's function
void CudaHandler::callCuda(){
	vector=myCudaTest(&len);
}	
//function who return the vector generated by cuda
float * CudaHandler::McudaTest(){
	if(len<0){
		callCuda();
	}
	return vector;
}
//function for release the memory of the vector
void CudaHandler::clear_vector(){
	delete[] vector;
}
//funciton who return the lenght of the vector
int CudaHandler::get_len(){
	return len;
}