//object who manage cuda's call
class CudaHandler{
private:
	//var who save the lenght of the vector
	int len= -1;
	//vector returned from cuda code
	float * vector;
	//function who call cuda code
	void CudaHandler::callCuda();
public:
	//function who return the vector generated by cuda
	float * CudaHandler::McudaTest();
	//function for release the memory of the vector
	void clear_vector();
	//funciton who return the lenght of the vector
	int get_len();
};